"""
OpenAI Agent Entry Point Template

This file is generated by AgentReady. Fill in your OpenAI agent logic here.
"""

import openai

def run_openai_agent(prompt: str, model: str = "gpt-4") -> str:
    response = openai.ChatCompletion.create(
        model=model,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

if __name__ == "__main__":
    import sys
    prompt = sys.argv[1] if len(sys.argv) > 1 else "Hello, OpenAI!"
    print(run_openai_agent(prompt))
