#!/usr/bin/env python3
"""
Repo-to-Agentic Transformer

Transforms any repository into an AI-agent-ready codebase by detecting:
- Languages, frameworks, and build systems
- Entry points and test frameworks
- Environment configuration
- Code conventions

Then generates:
- agent-context.json (machine-readable metadata)
- AGENTS.md (GitHub Copilot / OpenAI instructions)
- CLAUDE.md (Claude Code instructions)
- system_prompt.md (Universal LLM system prompt)
- mcp.json (MCP server configuration)
- Tool templates (language-specific)
- memory/schema.md (domain-specific memory schema)

Usage:
  python run_transformer.py --target /path/to/repo
  python run_transformer.py --target /path/to/repo --only agents
  python run_transformer.py --target /path/to/repo --dry-run
  python run_transformer.py --target /path/to/repo --provider anthropic

Generated by AgentReady (agent-ready) v1.1.0
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
TOOLKIT_ROOT = SCRIPT_DIR.parent
TEMPLATES_DIR = TOOLKIT_ROOT / "templates"

# Constants for language and framework detection
LANGUAGE_EXTENSIONS: dict[str, list[str]] = {
    "Python": [".py"],
    "TypeScript": [".ts", ".tsx"],
    "JavaScript": [".js", ".jsx", ".mjs", ".cjs"],
    "Java": [".java"],
    "Go": [".go"],
    "Rust": [".rs"],
    "C#": [".cs"],
    "Ruby": [".rb"],
    "C++": [".cpp", ".cc", ".cxx", ".hpp", ".h"],
    "C": [".c"],
    "PHP": [".php"],
    "Swift": [".swift"],
    "Kotlin": [".kt", ".kts"],
}

CONFIG_FILES: dict[str, dict[str, str]] = {
    "package.json": {"language": "JavaScript", "build": "npm"},
    "pyproject.toml": {"language": "Python", "build": "pip"},
    "requirements.txt": {"language": "Python", "build": "pip"},
    "go.mod": {"language": "Go", "build": "go"},
    "Cargo.toml": {"language": "Rust", "build": "cargo"},
    "pom.xml": {"language": "Java", "build": "maven"},
    "build.gradle": {"language": "Java", "build": "gradle"},
    "Gemfile": {"language": "Ruby", "build": "bundler"},
}

FRAMEWORK_INDICATORS: dict[str, list[str]] = {
    "React": ["react", "react-dom"],
    "Next.js": ["next"],
    "Vue": ["vue"],
    "Angular": ["@angular/core"],
    "Express": ["express"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "Flask": ["flask"],
    "Spring Boot": ["spring-boot-starter"],
    "Rails": ["rails"],
}

IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    ".tox", ".mypy_cache", ".pytest_cache", "dist", "build", "target",
    ".next", ".nuxt", "out", "coverage", ".idea", ".vscode",
}

# ============================================================================
# Repository Analysis
# ============================================================================

class RepoAnalyzer:
    """Analyzes a repository to extract metadata for agent scaffolding."""

    def __init__(self, target: Path):
        self.target = target.resolve()
        self.name = self.target.name
        self.files: list[Path] = []
        self.languages: dict[str, int] = {}
        self.frameworks: list[str] = []
        self.build_system: str = "unknown"
        self.entry_points: list[str] = []
        self.test_framework: str = "unknown"
        self.test_directory: str = ""
        self.source_dirs: list[str] = []
        self.key_files: dict[str, str] = {}
        self.commands: dict[str, str] = {}
        self.description: str = ""
        self.env_vars: list[str] = []

    def analyze(self) -> dict[str, Any]:
        """Run full repository analysis."""
        print(f"🔍 Analyzing repository: {self.target}")

        # Walk directory
        for root, dirs, files in os.walk(self.target):
            dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
            for f in files:
                self.files.append(Path(root) / f)

        print(f"  📁 Found {len(self.files)} files")

        # Detection steps
        self._detect_languages()
        self._detect_build_system()
        self._detect_frameworks()
        self._detect_entry_points()
        self._detect_tests()
        self._detect_source_dirs()
        self._detect_key_files()
        self._detect_env_vars()
        self._read_description()
        self._infer_commands()

        return self._to_dict()

    def _detect_languages(self) -> None:
        """Detect languages by file extension frequency."""
        for f in self.files:
            ext = f.suffix.lower()
            for lang, exts in LANGUAGE_EXTENSIONS.items():
                if ext in exts:
                    self.languages[lang] = self.languages.get(lang, 0) + 1
                    break

        self.languages = dict(sorted(self.languages.items(), key=lambda x: x[1], reverse=True))
        if self.languages:
            print(f"  🌐 Languages: {', '.join(self.languages.keys())}")

    def _detect_build_system(self) -> None:
        """Detect build system from config files."""
        for config_file, info in CONFIG_FILES.items():
            if (self.target / config_file).exists():
                self.build_system = info["build"]
                break
        print(f"  🔧 Build system: {self.build_system}")

    def _detect_frameworks(self) -> None:
        """Detect frameworks from dependency files."""
        # Check package.json
        pkg_file = self.target / "package.json"
        if pkg_file.exists():
            try:
                pkg = json.loads(pkg_file.read_text(encoding="utf-8"))
                all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                for framework, indicators in FRAMEWORK_INDICATORS.items():
                    if any(ind in all_deps for ind in indicators):
                        if framework not in self.frameworks:
                            self.frameworks.append(framework)
            except (json.JSONDecodeError, OSError):
                pass

        # Check Python dependency files
        for req_file in ["requirements.txt", "pyproject.toml", "setup.py"]:
            req_path = self.target / req_file
            if req_path.exists():
                try:
                    content = req_path.read_text(encoding="utf-8").lower()
                    for framework, indicators in FRAMEWORK_INDICATORS.items():
                        if any(ind.lower() in content for ind in indicators):
                            if framework not in self.frameworks:
                                self.frameworks.append(framework)
                except OSError:
                    pass

        if self.frameworks:
            print(f"  📦 Frameworks: {', '.join(self.frameworks)}")

    def _detect_entry_points(self) -> None:
        """Find common entry point files."""
        entry_names = ["main", "app", "index", "server", "manage", "cli"]
        for f in self.files:
            if f.stem.lower() in entry_names and f.suffix in (".py", ".ts", ".js", ".go", ".java", ".rb", ".php"):
                rel_path = str(f.relative_to(self.target))
                if rel_path not in self.entry_points:
                    self.entry_points.append(rel_path)

        if self.entry_points:
            print(f"  🚀 Entry points: {', '.join(self.entry_points[:3])}")

    def _detect_tests(self) -> None:
        """Find test framework and directory."""
        test_dirs = ["test", "tests", "spec", "__tests__", "test_", "testing"]
        for d in test_dirs:
            if (self.target / d).is_dir():
                self.test_directory = d
                break

        # Detect test framework
        if (self.target / "pytest.ini").exists():
            self.test_framework = "pytest"
        elif (self.target / "jest.config.js").exists() or (self.target / "jest.config.ts").exists():
            self.test_framework = "jest"
        elif (self.target / ".rspec").exists():
            self.test_framework = "rspec"
        else:
            self.test_framework = "unknown"

    def _detect_source_dirs(self) -> None:
        """Identify primary source directories."""
        common_src_dirs = ["src", "lib", "app", "pkg", "internal", "cmd", "api"]
        for d in common_src_dirs:
            if (self.target / d).is_dir():
                self.source_dirs.append(d)

    def _detect_key_files(self) -> None:
        """Identify important files."""
        key_patterns = {
            "README.md": "Project documentation",
            "package.json": "Node.js dependencies",
            "pyproject.toml": "Python project config",
            "pom.xml": "Maven configuration",
            "build.gradle": "Gradle configuration",
            "Dockerfile": "Container definition",
            ".env.example": "Environment template",
        }
        for filename, desc in key_patterns.items():
            if (self.target / filename).exists():
                self.key_files[filename] = desc

    def _detect_env_vars(self) -> None:
        """Extract environment variables."""
        for env_file in [".env.example", ".env.sample"]:
            env_path = self.target / env_file
            if env_path.exists():
                try:
                    content = env_path.read_text(encoding="utf-8")
                    for line in content.splitlines():
                        if line.strip() and "=" in line and not line.startswith("#"):
                            var_name = line.split("=", 1)[0].strip()
                            self.env_vars.append(var_name)
                except OSError:
                    pass

    def _read_description(self) -> None:
        """Extract description from README."""
        readme = self.target / "README.md"
        if readme.exists():
            try:
                content = readme.read_text(encoding="utf-8")
                lines = content.splitlines()
                in_para = False
                para_lines = []
                for line in lines[1:]:
                    s = line.strip()
                    if not s and in_para:
                        break
                    if s and not s.startswith("#"):
                        in_para = True
                        para_lines.append(s)
                if para_lines:
                    self.description = " ".join(para_lines)[:300]
            except OSError:
                pass

        if not self.description:
            langs = ", ".join(list(self.languages.keys())[:2]) or "software"
            self.description = f"A {langs} project"

    def _infer_commands(self) -> None:
        """Infer build/test commands from build system."""
        cmd_map = {
            "npm": {
                "install": "npm install",
                "build": "npm run build",
                "test": "npm test",
                "run": "npm start",
            },
            "pip": {
                "install": "pip install -r requirements.txt",
                "build": "python -m build",
                "test": "pytest",
                "run": "python -m app",
            },
            "go": {
                "install": "go mod download",
                "build": "go build ./...",
                "test": "go test ./...",
                "run": "go run .",
            },
            "maven": {
                "install": "mvn install",
                "build": "mvn package",
                "test": "mvn test",
                "run": "mvn exec:java",
            },
            "gradle": {
                "install": "./gradlew dependencies",
                "build": "./gradlew build",
                "test": "./gradlew test",
                "run": "./gradlew run",
            },
        }
        self.commands = cmd_map.get(self.build_system, {})

    def _to_dict(self) -> dict[str, Any]:
        """Convert analysis to dictionary."""
        return {
            "project_name": self.name,
            "description": self.description,
            "primary_languages": list(self.languages.keys()),
            "frameworks": self.frameworks,
            "build_system": self.build_system,
            "entry_points": self.entry_points,
            "test_framework": self.test_framework,
            "test_directory": self.test_directory,
            "source_directories": self.source_dirs,
            "key_files": self.key_files,
            "commands": self.commands,
            "environment_variables": self.env_vars,
        }


# ============================================================================
# File Generation
# ============================================================================

class AgenticGenerator:
    """Generates AI-agent-ready files."""

    def __init__(self, target: Path, metadata: dict[str, Any], dry_run: bool = False, force: bool = False):
        self.target = target
        self.meta = metadata
        self.dry_run = dry_run
        self.force = force
        self.generated: list[tuple[str, str]] = []  # (file, status)

    def generate_all(self) -> list[tuple[str, str]]:
        """Generate all files."""
        self._generate_context_json()
        self._generate_agents_md()
        self._generate_claude_md()
        self._generate_system_prompt()
        self._generate_mcp_json()
        self._generate_tool_templates()
        self._generate_memory_schema()
        return self.generated

    def generate_only(self, category: str) -> list[tuple[str, str]]:
        """Generate only specific category."""
        if category == "agents":
            self._generate_agents_md()
            self._generate_claude_md()
            self._generate_system_prompt()
        elif category == "tools":
            self._generate_tool_templates()
        elif category == "context":
            self._generate_context_json()
        elif category == "memory":
            self._generate_memory_schema()
        else:
            print(f"❌ Unknown category: {category}")
            sys.exit(1)
        return self.generated

    def _write_file(self, rel_path: str, content: str) -> str:
        """Write file, return status."""
        full_path = self.target / rel_path
        if full_path.exists() and not self.force:
            status = "⏭️  Skipped"
        else:
            if self.dry_run:
                status = "📝 (dry-run)"
            else:
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content, encoding="utf-8")
                status = "✅ Created" if not full_path.exists() or self.force else "🔄 Updated"
            self.generated.append((rel_path, status))
            print(f"  {status[0:2]} {rel_path}")
        return status

    def _fill_template(self, template_content: str) -> str:
        """Fill template placeholders."""
        m = self.meta
        replacements = {
            "{{PROJECT_NAME}}": m.get("project_name", "Project"),
            "{{PROJECT_DESCRIPTION}}": m.get("description", ""),
            "{{PRIMARY_LANGUAGES}}": ", ".join(m.get("primary_languages", [])) or "Unknown",
            "{{FRAMEWORKS}}": ", ".join(m.get("frameworks", [])) or "None",
            "{{BUILD_SYSTEM}}": m.get("build_system", "unknown"),
            "{{TEST_FRAMEWORK}}": m.get("test_framework", "unknown"),
            "{{TEST_DIRECTORY}}": m.get("test_directory", "tests/"),
            "{{INSTALL_COMMAND}}": m.get("commands", {}).get("install", "# <TODO: verify>"),
            "{{BUILD_COMMAND}}": m.get("commands", {}).get("build", "# <TODO: verify>"),
            "{{RUN_COMMAND}}": m.get("commands", {}).get("run", "# <TODO: verify>"),
            "{{TEST_COMMAND}}": m.get("commands", {}).get("test", "# <TODO: verify>"),
            "{{TIMESTAMP}}": datetime.now(timezone.utc).isoformat(),
        }
        result = template_content
        for placeholder, value in replacements.items():
            result = result.replace(placeholder, str(value))
        return result

    def _generate_context_json(self) -> None:
        """Generate agent-context.json with static/dynamic split. (FIX 5)"""
        context_file = self.target / "agent-context.json"
        
        # Prepare static section (set once, rarely changes)
        static_section = {
            "_comment": "These fields are set once. Edit manually. Never overwritten by the transformer.",
            "repo_name": self.meta.get("project_name", "Project"),
            "primary_language": self.meta.get("primary_languages", ["Unknown"])[0],
            "language_version": self.meta.get("build_system", "unknown"),
            "frameworks": self.meta.get("frameworks", []),
            "entry_point": self.meta.get("entry_points", [""])[0] if self.meta.get("entry_points") else "",
            "api_protocol": "REST",
            "restricted_write_paths": [],
            "environment_variables": {var: "<description>" for var in self.meta.get("environment_variables", [])},
        }
        
        # Prepare dynamic section (refreshed on every scan)
        dynamic_section = {
            "_comment": "These fields are refreshed automatically on every scan.",
            "last_scanned": datetime.now(timezone.utc).isoformat(),
            "module_layout": {"src/": "Source code", "tests/": "Test code"},
            "domain_concepts": [],
            "agent_capabilities": ["code_analysis", "testing", "building"],
            "test_command": self.meta.get("commands", {}).get("test", "unknown"),
            "build_command": self.meta.get("commands", {}).get("build", "unknown"),
            "lint_command": "",
        }
        
        # If file exists, preserve static section
        if context_file.exists():
            try:
                existing = json.loads(context_file.read_text())
                if "static" in existing:
                    static_section.update(existing.get("static", {}))
            except json.JSONDecodeError:
                pass
        
        context = {
            "static": static_section,
            "dynamic": dynamic_section,
        }
        
        content = json.dumps(context, indent=2, ensure_ascii=False)
        self._write_file("agent-context.json", content)

    def _generate_agents_md(self) -> None:
        """Generate AGENTS.md."""
        template_path = TEMPLATES_DIR / "AGENTS.template.md"
        if template_path.exists():
            content = template_path.read_text(encoding="utf-8")
            filled = self._fill_template(content)
            self._write_file("AGENTS.md", filled)

    def _generate_claude_md(self) -> None:
        """Generate CLAUDE.md."""
        template_path = TEMPLATES_DIR / "CLAUDE.template.md"
        if template_path.exists():
            content = template_path.read_text(encoding="utf-8")
            filled = self._fill_template(content)
            self._write_file("CLAUDE.md", filled)

    def _generate_system_prompt(self) -> None:
        """Generate system_prompt.md."""
        template_path = TEMPLATES_DIR / "system_prompt.template.md"
        if template_path.exists():
            content = template_path.read_text(encoding="utf-8")
            filled = self._fill_template(content)
            self._write_file("system_prompt.md", filled)

    def _generate_mcp_json(self) -> None:
        """Generate mcp.json."""
        template_path = TEMPLATES_DIR / "mcp.template.json"
        if template_path.exists():
            content = template_path.read_text(encoding="utf-8")
            filled = self._fill_template(content)
            self._write_file("mcp.json", filled)

    def _generate_tool_templates(self) -> None:
        """Generate tool templates for detected languages."""
        lang_to_template = {
            "Python": "tool.python.template.py",
            "TypeScript": "tool.typescript.template.ts",
            "JavaScript": "tool.typescript.template.ts",
            "Java": "tool.java.template.java",
            "Go": "tool.go.template.go",
        }
        lang_to_output = {
            "Python": "tools/example_tool.py",
            "TypeScript": "tools/example_tool.ts",
            "JavaScript": "tools/example_tool.ts",
            "Java": "tools/ExampleTool.java",
            "Go": "tools/example_tool.go",
        }

        generated = set()
        for lang in self.meta.get("primary_languages", []):
            template_file = lang_to_template.get(lang)
            output_file = lang_to_output.get(lang)
            if template_file and output_file and output_file not in generated:
                template_path = TEMPLATES_DIR / template_file
                if template_path.exists():
                    content = template_path.read_text(encoding="utf-8")
                    self._write_file(output_file, content)
                    generated.add(output_file)

    def _generate_memory_schema(self) -> None:
        """Generate minimal memory schema."""
        schema = {
            "version": "1.0.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "project": self.meta.get("project_name", "Project"),
            "languages": self.meta.get("primary_languages", []),
            "frameworks": self.meta.get("frameworks", []),
            "conventions": {
                "test_framework": self.meta.get("test_framework", "unknown"),
                "entry_points": self.meta.get("entry_points", []),
            },
        }
        content = json.dumps(schema, indent=2, ensure_ascii=False)
        self._write_file("memory/schema.md", f"```json\n{content}\n```\n")


# ============================================================================
# Pre-commit Hook Management
# ============================================================================

def install_hooks(target_path: Path) -> None:
    """Install pre-commit hook for automatic context refresh. (FIX 2)"""
    git_hooks_dir = target_path / ".git" / "hooks"
    hook_path = git_hooks_dir / "pre-commit"
    
    hook_content = '''#!/bin/sh
# Installed by legacy-to-agentic-ready — keeps agent-context.json fresh.
# Re-scans only if source files changed. Fails commit if context is stale.

CHANGED=$(git diff --cached --name-only | grep -E '\\.(py|ts|js|java|go|rs|cs|rb)$')
if [ -z "$CHANGED" ]; then
  exit 0
fi

TOOLKIT=$(git config --get agentic.toolkit-path)
if [ -z "$TOOLKIT" ]; then
  echo "[agentic-ready] Skipping context refresh — agentic.toolkit-path not set."
  echo "  Run: git config agentic.toolkit-path /path/to/legacy-to-agentic-ready"
  exit 0
fi

echo "[agentic-ready] Source files changed — refreshing agent-context.json..."
python "$TOOLKIT/scripts/run_transformer.py" --target . --only context --force --quiet

if ! git diff --quiet agent-context.json; then
  git add agent-context.json
  echo "[agentic-ready] agent-context.json updated and staged."
fi
'''
    
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    
    if hook_path.exists() and not hook_path.read_text().find("legacy-to-agentic-ready") >= 0:
        print(f"⚠️  A pre-commit hook already exists at {hook_path}.")
        print("To install manually, append the contents of:")
        print("scripts/pre-commit-snippet.sh")
        return
    
    hook_path.write_text(hook_content, encoding="utf-8")
    os.chmod(hook_path, 0o755)
    
    print(f"✅ Pre-commit hook installed in {hook_path}")
    print("To enable context refresh, run:")
    print("git config agentic.toolkit-path /absolute/path/to/legacy-to-agentic-ready")


# ============================================================================
# Context Verification
# ============================================================================

def verify(target_path: Path) -> None:
    """Verify generated context with LLM. (FIX 4)"""
    context_file = target_path / "agent-context.json"
    claude_file = target_path / "CLAUDE.md"
    
    if not context_file.exists():
        print("⚠️  agent-context.json not found. Skipping verification.")
        return
    
    try:
        context_json = json.loads(context_file.read_text())
    except json.JSONDecodeError:
        print("❌ agent-context.json is malformed JSON")
        return
    
    claude_md = claude_file.read_text() if claude_file.exists() else ""
    
    # Try to use Anthropic API if available
    try:
        import anthropic
        
        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        prompt = f"""Given the following agent-context.json and CLAUDE.md from a software repository,
answer these three questions in valid JSON only, no other text:
{{
"detected_entry_point": "what is the entry point file?",
"detected_test_command": "what command runs the tests?",
"detected_primary_language": "what is the primary language?"
}}

agent-context.json:
{json.dumps(context_json, indent=2)}

CLAUDE.md:
{claude_md}"""
        
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=256,
            messages=[{"role": "user", "content": prompt}],
        )
        
        try:
            response_text = message.content[0].text
            llm_answers = json.loads(response_text)
        except (json.JSONDecodeError, IndexError):
            print("⚠️  LLM response was not valid JSON. Skipping verification.")
            return
        
        # Compare
        entry_point = context_json.get("entry_points", ["<unknown>"])[0] if context_json.get("entry_points") else "<unknown>"
        test_cmd = context_json.get("commands", {}).get("test", "<unknown>")
        lang = context_json.get("primary_languages", ["<unknown>"])[0] if context_json.get("primary_languages") else "<unknown>"
        
        results = [
            ("entry_point", entry_point, llm_answers.get("detected_entry_point", "<unknown>")),
            ("test_command", test_cmd, llm_answers.get("detected_test_command", "<unknown>")),
            ("primary_language", lang, llm_answers.get("detected_primary_language", "<unknown>")),
        ]
        
        # Print table
        print()
        print("┌─────────────────────┬──────────────────────┬──────────────────────┬────────┐")
        print("│ Field               │ agent-context.json   │ LLM understood       │ Match  │")
        print("├─────────────────────┼──────────────────────┼──────────────────────┼────────┤")
        
        matched = 0
        for field, actual, understood in results:
            match = "✅" if str(actual).lower() in str(understood).lower() or str(understood).lower() in str(actual).lower() else "❌"
            if "✅" in match:
                matched += 1
            print(f"│ {field:<19} │ {str(actual)[:20]:<20} │ {str(understood)[:20]:<20} │ {match:<6} │".ljust(80))
        
        print("└─────────────────────┴──────────────────────┴──────────────────────┴────────┘")
        print(f"Verification score: {matched}/3")
        print()
        
        if matched < 2:
            sys.exit(1)
    except ImportError:
        print("⚠️  anthropic package not installed. Skipping LLM verification.")


# ============================================================================
# Agentic Readiness Scoring
# ============================================================================

def score(target_path: Path) -> dict[str, Any]:
    """Calculate agentic readiness score. (FIX 6)"""
    criteria = {
        "agent-context.json": (10, (target_path / "agent-context.json").exists()),
        "CLAUDE.md": (10, (target_path / "CLAUDE.md").exists()),
        "AGENTS.md": (10, (target_path / "AGENTS.md").exists()),
        "system_prompt.md": (5, (target_path / "system_prompt.md").exists() or (target_path / "agents" / "system_prompt.md").exists()),
        "tools/ has files": (10, any((target_path / "tools").glob("*"))),
    }
    
    context_file = target_path / "agent-context.json"
    if context_file.exists():
        try:
            ctx = json.loads(context_file.read_text())
            entry_point = ctx.get("entry_points", [""])[0] if ctx.get("entry_points") else ""
            criteria["entry_point exists"] = (10, bool(entry_point) and (target_path / entry_point).exists())
            criteria["test_command set"] = (10, bool(ctx.get("commands", {}).get("test")))
            criteria["restricted_write_paths"] = (10, len(ctx.get("restricted_write_paths", [])) > 0)
            criteria["environment_variables"] = (10, len(ctx.get("environment_variables", [])) > 0)
        except json.JSONDecodeError:
            pass
    
    criteria["domain_concepts ≥3"] = (5, len(context_file.exists() and json.loads(context_file.read_text()).get("domain_concepts", []) or []) >= 3)
    criteria["OpenAPI spec"] = (5, any([
        list(target_path.glob("**/openapi.yaml")),
        list(target_path.glob("**/openapi.yml")),
        list(target_path.glob("**/openapi.json")),
        list(target_path.glob("**/swagger.yaml")),
        list(target_path.glob("**/swagger.yml")),
        list(target_path.glob("**/swagger.json")),
    ]))
    criteria["CI config exists"] = (5, any(target_path.glob(".github/workflows/*.yml")) or any(target_path.glob(".gitea/workflows/*.yml")))
    
    total = 0
    table_rows = []
    for criterion, (points, achieved) in criteria.items():
        if achieved:
            total += points
            table_rows.append((f"✅ {criterion}", f"+{points}"))
        else:
            table_rows.append((f"⬜ {criterion}", f"+ 0"))
    
    return {"score": total, "max": 100, "rows": table_rows}


# ============================================================================
# CLI
# ============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Transform any repository into an AI-agent-ready codebase.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run_transformer.py --target /path/to/repo
  python run_transformer.py --target /path/to/repo --only agents
  python run_transformer.py --target /path/to/repo --dry-run
  python run_transformer.py --target /path/to/repo --force
  python run_transformer.py --target /path/to/repo --provider anthropic
        """,
    )
    parser.add_argument("--target", "-t", required=True, help="Target repository path")
    parser.add_argument(
        "--only",
        choices=["agents", "tools", "context", "memory"],
        help="Generate only specific category",
    )
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai", "gemini"],
        default="anthropic",
        help="LLM provider for enhanced generation",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--install-hooks", action="store_true", help="Install pre-commit hook")
    parser.add_argument("--verify", action="store_true", help="Verify generated context with LLM")
    parser.add_argument("--quiet", action="store_true", help="Suppress non-essential output")

    args = parser.parse_args()
    target = Path(args.target).resolve()

    if not target.is_dir():
        print(f"❌ Directory not found: {target}")
        sys.exit(1)

    # Handle install-hooks flag
    if args.install_hooks:
        install_hooks(target)
        return
    
    # Handle verify flag
    if args.verify:
        verify(target)
        return

    if not args.quiet:
        print()
        print("╔══════════════════════════════════════════════╗")
        print("║   🤖 AgentReady Transformer v1.1.0          ║")
        print("╚══════════════════════════════════════════════╝")
        print()

    # Analyze
    analyzer = RepoAnalyzer(target)
    metadata = analyzer.analyze()

    if not args.quiet:
        print()

    # Generate
    generator = AgenticGenerator(target, metadata, dry_run=args.dry_run, force=args.force)
    if args.only:
        generated = generator.generate_only(args.only)
    else:
        generated = generator.generate_all()

    # Scoring
    readiness = score(target)
    
    # Summary
    if not args.quiet:
        print()
        print("─" * 50)
        mode_str = "[DRY RUN] " if args.dry_run else ""
        print(f"✅ {mode_str}Transformation Complete")
        print("─" * 50)
        print(f"  Project:    {metadata['project_name']}")
        print(f"  Languages:  {', '.join(metadata['primary_languages']) or 'Unknown'}")
        print(f"  Build:      {metadata['build_system']}")
        print()
        print("  Generated Files:")
        for filepath, status in generated:
            print(f"    {status} {filepath}")
        print()
        print("  No existing files were modified." if not args.force else "  Files updated with --force flag.")
        print()
        
        # Print readiness score
        print("──────────────────────────────────────")
        print(f"AGENTIC READINESS SCORE: {readiness['score']} / {readiness['max']}")
        print("──────────────────────────────────────")
        for criterion, points in readiness["rows"]:
            print(f"  {criterion:<40} {points:>3}")
        if readiness["score"] < 100:
            print()
            print("💡 To improve your score:")
            if not (target / "agent-context.json").exists():
                print("- Generate agent-context.json (run without --only flag)")
            if not (target / ".env.example").exists():
                print("- Add environment_variables to agent-context.json")
            if not any(target.glob("**/openapi.{yaml,json,yml}")):
                print("- Add an OpenAPI spec (openapi.yaml) for better tool generation")
        print("──────────────────────────────────────")
        print()


if __name__ == "__main__":
    main()
