#!/usr/bin/env python3
"""
AgentReady — CLI Transformer

Transforms any repository into an AI-agent-ready codebase by detecting:
- Languages, frameworks, and build systems
- Entry points and test frameworks
- Environment configuration
- Code conventions

Then generates:
- agent-context.json (machine-readable metadata)
- AGENTS.md (GitHub Copilot / OpenAI instructions)
- CLAUDE.md (Claude Code instructions)
- system_prompt.md (Universal LLM system prompt)
- mcp.json (MCP server configuration)
- Tool templates (language-specific)
- memory/schema.md (domain-specific memory schema)

Usage:
  python run_transformer.py --target /path/to/repo
  python run_transformer.py --target /path/to/repo --llm
  python run_transformer.py --target /path/to/repo --only agents
  python run_transformer.py --target /path/to/repo --dry-run
  python run_transformer.py --target /path/to/repo --llm --eval
  python run_transformer.py --target /path/to/repo --eval-only
  python run_transformer.py --target /path/to/repo --eval-only --fail-level 0.8

Generated by AgentReady (agent-ready) v2.0.0
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
TOOLKIT_ROOT = SCRIPT_DIR.parent.parent

_PKG_TEMPLATES = SCRIPT_DIR / "templates"
_REPO_TEMPLATES = TOOLKIT_ROOT / "templates"
TEMPLATES_DIR = _PKG_TEMPLATES if _PKG_TEMPLATES.is_dir() else _REPO_TEMPLATES

LANGUAGE_EXTENSIONS: dict[str, list[str]] = {
    "Python": [".py"],
    "TypeScript": [".ts", ".tsx"],
    "JavaScript": [".js", ".jsx", ".mjs", ".cjs"],
    "Java": [".java"],
    "Go": [".go"],
    "Rust": [".rs"],
    "C#": [".cs"],
    "Ruby": [".rb"],
    "C++": [".cpp", ".cc", ".cxx", ".hpp", ".h"],
    "C": [".c"],
    "PHP": [".php"],
    "Swift": [".swift"],
    "Kotlin": [".kt", ".kts"],
}

CONFIG_FILES: dict[str, dict[str, str]] = {
    "package.json": {"language": "JavaScript", "build": "npm"},
    "pyproject.toml": {"language": "Python", "build": "pip"},
    "requirements.txt": {"language": "Python", "build": "pip"},
    "go.mod": {"language": "Go", "build": "go"},
    "Cargo.toml": {"language": "Rust", "build": "cargo"},
    "pom.xml": {"language": "Java", "build": "maven"},
    "build.gradle": {"language": "Java", "build": "gradle"},
    "Gemfile": {"language": "Ruby", "build": "bundler"},
}

FRAMEWORK_INDICATORS: dict[str, list[str]] = {
    "React": ["react", "react-dom"],
    "Next.js": ["next"],
    "Vue": ["vue"],
    "Angular": ["@angular/core"],
    "Express": ["express"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "Flask": ["flask"],
    "Spring Boot": ["spring-boot-starter"],
    "Rails": ["rails"],
}

IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "env",
    ".tox", ".mypy_cache", ".pytest_cache", "dist", "build", "target",
    ".next", ".nuxt", "out", "coverage", ".idea", ".vscode",
}


# ============================================================================
# Repository Analysis
# ============================================================================

class RepoAnalyzer:
    def __init__(self, target: Path):
        self.target = target.resolve()
        self.name = self.target.name
        self.files: list[Path] = []
        self.languages: dict[str, int] = {}
        self.frameworks: list[str] = []
        self.build_system: str = "unknown"
        self.entry_points: list[str] = []
        self.test_framework: str = "unknown"
        self.test_directory: str = ""
        self.source_dirs: list[str] = []
        self.key_files: dict[str, str] = {}
        self.commands: dict[str, str] = {}
        self.description: str = ""
        self.env_vars: list[str] = []

    def analyze(self) -> dict[str, Any]:
        print(f"🔍 Analyzing repository: {self.target}")
        for root, dirs, files in os.walk(self.target):
            dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
            for f in files:
                self.files.append(Path(root) / f)
        print(f"  📁 Found {len(self.files)} files")
        self._detect_languages()
        self._detect_build_system()
        self._detect_frameworks()
        self._detect_entry_points()
        self._detect_tests()
        self._detect_source_dirs()
        self._detect_key_files()
        self._detect_env_vars()
        self._read_description()
        self._infer_commands()
        return self._to_dict()

    def _detect_languages(self) -> None:
        for f in self.files:
            ext = f.suffix.lower()
            for lang, exts in LANGUAGE_EXTENSIONS.items():
                if ext in exts:
                    self.languages[lang] = self.languages.get(lang, 0) + 1
                    break
        self.languages = dict(sorted(self.languages.items(), key=lambda x: x[1], reverse=True))
        if self.languages:
            print(f"  🌐 Languages: {', '.join(self.languages.keys())}")

    def _detect_build_system(self) -> None:
        for config_file, info in CONFIG_FILES.items():
            if (self.target / config_file).exists():
                self.build_system = info["build"]
                break
        print(f"  🔧 Build system: {self.build_system}")

    def _detect_frameworks(self) -> None:
        pkg_file = self.target / "package.json"
        if pkg_file.exists():
            try:
                pkg = json.loads(pkg_file.read_text(encoding="utf-8"))
                all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                for framework, indicators in FRAMEWORK_INDICATORS.items():
                    if any(ind in all_deps for ind in indicators):
                        if framework not in self.frameworks:
                            self.frameworks.append(framework)
            except (json.JSONDecodeError, OSError):
                pass
        for req_file in ["requirements.txt", "pyproject.toml", "setup.py"]:
            req_path = self.target / req_file
            if req_path.exists():
                try:
                    content = req_path.read_text(encoding="utf-8").lower()
                    for framework, indicators in FRAMEWORK_INDICATORS.items():
                        if any(ind.lower() in content for ind in indicators):
                            if framework not in self.frameworks:
                                self.frameworks.append(framework)
                except OSError:
                    pass
        for build_file in ["pom.xml", "build.gradle", "build.gradle.kts"]:
            build_path = self.target / build_file
            if build_path.exists():
                try:
                    content = build_path.read_text(encoding="utf-8").lower()
                    for framework, indicators in FRAMEWORK_INDICATORS.items():
                        if any(ind.lower() in content for ind in indicators):
                            if framework not in self.frameworks:
                                self.frameworks.append(framework)
                except OSError:
                    pass
        if self.frameworks:
            print(f"  📦 Frameworks: {', '.join(self.frameworks)}")

    def _detect_entry_points(self) -> None:
        entry_names = ["main", "app", "index", "server", "manage", "cli"]
        for f in self.files:
            if f.stem.lower() in entry_names and f.suffix in (".py", ".ts", ".js", ".go", ".java", ".rb", ".php"):
                rel_path = str(f.relative_to(self.target))
                if rel_path not in self.entry_points:
                    self.entry_points.append(rel_path)
        if self.entry_points:
            print(f"  🚀 Entry points: {', '.join(self.entry_points[:3])}")

    def _detect_tests(self) -> None:
        for d in ["test", "tests", "spec", "__tests__", "test_", "testing"]:
            if (self.target / d).is_dir():
                self.test_directory = d
                break
        if (self.target / "pytest.ini").exists():
            self.test_framework = "pytest"
        elif (self.target / "jest.config.js").exists() or (self.target / "jest.config.ts").exists():
            self.test_framework = "jest"
        elif (self.target / ".rspec").exists():
            self.test_framework = "rspec"

    def _detect_source_dirs(self) -> None:
        for d in ["src", "lib", "app", "pkg", "internal", "cmd", "api"]:
            if (self.target / d).is_dir():
                self.source_dirs.append(d)

    def _detect_key_files(self) -> None:
        key_patterns = {
            "README.md": "Project documentation",
            "package.json": "Node.js dependencies",
            "pyproject.toml": "Python project config",
            "pom.xml": "Maven configuration",
            "build.gradle": "Gradle configuration",
            "Dockerfile": "Container definition",
            ".env.example": "Environment template",
        }
        for filename, desc in key_patterns.items():
            if (self.target / filename).exists():
                self.key_files[filename] = desc

    def _detect_env_vars(self) -> None:
        for env_file in [".env.example", ".env.sample"]:
            env_path = self.target / env_file
            if env_path.exists():
                try:
                    content = env_path.read_text(encoding="utf-8")
                    for line in content.splitlines():
                        if line.strip() and "=" in line and not line.startswith("#"):
                            self.env_vars.append(line.split("=", 1)[0].strip())
                except OSError:
                    pass

    def _read_description(self) -> None:
        readme = self.target / "README.md"
        if readme.exists():
            try:
                content = readme.read_text(encoding="utf-8")
                in_para = False
                para_lines = []
                for line in content.splitlines()[1:]:
                    s = line.strip()
                    if not s and in_para:
                        break
                    if s and not s.startswith("#"):
                        in_para = True
                        para_lines.append(s)
                if para_lines:
                    self.description = " ".join(para_lines)[:300]
            except OSError:
                pass
        if not self.description:
            langs = ", ".join(list(self.languages.keys())[:2]) or "software"
            self.description = f"A {langs} project"

    def _infer_commands(self) -> None:
        cmd_map = {
            "npm": {"install": "npm install", "build": "npm run build", "test": "npm test", "run": "npm start"},
            "pip": {"install": "pip install -r requirements.txt", "build": "python -m build", "test": "pytest", "run": "python -m app"},
            "go": {"install": "go mod download", "build": "go build ./...", "test": "go test ./...", "run": "go run ."},
            "maven": {"install": "mvn install", "build": "mvn package", "test": "mvn test", "run": "mvn exec:java"},
            "gradle": {"install": "./gradlew dependencies", "build": "./gradlew build", "test": "./gradlew test", "run": "./gradlew run"},
        }
        self.commands = cmd_map.get(self.build_system, {})

    def _to_dict(self) -> dict[str, Any]:
        return {
            "project_name": self.name,
            "description": self.description,
            "primary_languages": list(self.languages.keys()),
            "frameworks": self.frameworks,
            "build_system": self.build_system,
            "entry_points": self.entry_points,
            "test_framework": self.test_framework,
            "test_directory": self.test_directory,
            "source_directories": self.source_dirs,
            "key_files": self.key_files,
            "commands": self.commands,
            "environment_variables": self.env_vars,
        }


# ============================================================================
# File Generation (static / template-based)
# ============================================================================

class AgenticGenerator:
    def __init__(self, target: Path, metadata: dict[str, Any], dry_run: bool = False, force: bool = False):
        self.target = target
        self.meta = metadata
        self.dry_run = dry_run
        self.force = force
        self.generated: list[tuple[str, str]] = []

    def generate_all(self) -> list[tuple[str, str]]:
        self._generate_context_json()
        self._generate_agents_md()
        self._generate_claude_md()
        self._generate_system_prompt()
        self._generate_mcp_json()
        self._generate_tool_templates()
        self._generate_openai_agent()
        self._generate_gemini_agent()
        self._generate_memory_schema()
        try:
            readiness = score(Path(self.target))
            print(f"AGENTIC READINESS SCORE: {readiness['score']} / {readiness['max']}")
        except Exception as e:
            print(f"[WARN] Could not calculate readiness score: {e}")
        return self.generated

    def _generate_openai_agent(self) -> None:
        template_path = TEMPLATES_DIR / "openai_agent.template.py"
        if template_path.exists():
            self._write_file("agents/openai_agent.py", template_path.read_text(encoding="utf-8"))

    def _generate_gemini_agent(self) -> None:
        template_path = TEMPLATES_DIR / "gemini_agent.template.yaml"
        if template_path.exists():
            self._write_file("agents/gemini_agent.yaml", template_path.read_text(encoding="utf-8"))

    def generate_only(self, category: str) -> list[tuple[str, str]]:
        dispatch = {
            "agents": lambda: (self._generate_agents_md(), self._generate_claude_md(), self._generate_system_prompt()),
            "tools": self._generate_tool_templates,
            "context": self._generate_context_json,
            "memory": self._generate_memory_schema,
        }
        fn = dispatch.get(category)
        if fn is None:
            print(f"❌ Unknown category: {category}")
            sys.exit(1)
        fn()
        return self.generated

    def _write_file(self, rel_path: str, content: str) -> str:
        full_path = self.target / rel_path
        already_exists = full_path.exists()
        if already_exists and not self.force:
            status = "⏭️  Skipped"
            self.generated.append((rel_path, status))
            print(f"  ⏭️  {rel_path} (already exists, use --force to overwrite)")
        else:
            if self.dry_run:
                status = "📝 (dry-run)"
            else:
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content, encoding="utf-8")
                status = "🔄 Updated" if already_exists else "✅ Created"
            self.generated.append((rel_path, status))
            print(f"  {status[0:2]} {rel_path}")
        return status

    def _fill_template(self, template_content: str) -> str:
        m = self.meta
        replacements = {
            "{{PROJECT_NAME}}": m.get("project_name", "Project"),
            "{{PROJECT_DESCRIPTION}}": m.get("description", ""),
            "{{PRIMARY_LANGUAGES}}": ", ".join(m.get("primary_languages", [])) or "Unknown",
            "{{FRAMEWORKS}}": ", ".join(m.get("frameworks", [])) or "None",
            "{{BUILD_SYSTEM}}": m.get("build_system", "unknown"),
            "{{TEST_FRAMEWORK}}": m.get("test_framework", "unknown"),
            "{{TEST_DIRECTORY}}": m.get("test_directory", "tests/"),
            "{{INSTALL_COMMAND}}": m.get("commands", {}).get("install", "# <TODO: verify>"),
            "{{BUILD_COMMAND}}": m.get("commands", {}).get("build", "# <TODO: verify>"),
            "{{RUN_COMMAND}}": m.get("commands", {}).get("run", "# <TODO: verify>"),
            "{{TEST_COMMAND}}": m.get("commands", {}).get("test", "# <TODO: verify>"),
            "{{TIMESTAMP}}": datetime.now(timezone.utc).isoformat(),
        }
        result = template_content
        for placeholder, value in replacements.items():
            result = result.replace(placeholder, str(value))
        return result

    def _generate_context_json(self) -> None:
        context_file = self.target / "agent-context.json"
        static_section = {
            "_comment": "These fields are set once. Edit manually. Never overwritten by the transformer.",
            "repo_name": self.meta.get("project_name", "Project"),
            "primary_language": self.meta.get("primary_languages", ["Unknown"])[0],
            "language_version": self.meta.get("build_system", "unknown"),
            "frameworks": self.meta.get("frameworks", []),
            "entry_point": self.meta.get("entry_points", [""])[0] if self.meta.get("entry_points") else "",
            "api_protocol": "REST",
            "restricted_write_paths": [],
            "environment_variables": {var: "<description>" for var in self.meta.get("environment_variables", [])},
        }
        dynamic_section = {
            "_comment": "These fields are refreshed automatically on every scan.",
            "last_scanned": datetime.now(timezone.utc).isoformat(),
            "module_layout": {"src/": "Source code", "tests/": "Test code"},
            "domain_concepts": [],
            "agent_capabilities": ["code_analysis", "testing", "building"],
            "test_command": self.meta.get("commands", {}).get("test", "unknown"),
            "build_command": self.meta.get("commands", {}).get("build", "unknown"),
            "lint_command": "",
        }
        if context_file.exists():
            try:
                existing = json.loads(context_file.read_text())
                if "static" in existing:
                    static_section.update(existing.get("static", {}))
            except json.JSONDecodeError:
                pass
        self._write_file("agent-context.json", json.dumps({"static": static_section, "dynamic": dynamic_section}, indent=2, ensure_ascii=False))

    def _generate_agents_md(self) -> None:
        t = TEMPLATES_DIR / "AGENTS.template.md"
        if t.exists():
            self._write_file("AGENTS.md", self._fill_template(t.read_text(encoding="utf-8")))

    def _generate_claude_md(self) -> None:
        t = TEMPLATES_DIR / "CLAUDE.template.md"
        if t.exists():
            self._write_file("CLAUDE.md", self._fill_template(t.read_text(encoding="utf-8")))

    def _generate_system_prompt(self) -> None:
        t = TEMPLATES_DIR / "system_prompt.template.md"
        if t.exists():
            self._write_file("system_prompt.md", self._fill_template(t.read_text(encoding="utf-8")))
        else:
            print("[WARN] system_prompt.template.md not found.")

    def _generate_mcp_json(self) -> None:
        t = TEMPLATES_DIR / "mcp.template.json"
        if t.exists():
            self._write_file("mcp.json", self._fill_template(t.read_text(encoding="utf-8")))

    def _generate_tool_templates(self) -> None:
        lang_map = {
            "Python": ("tool.python.template.py", "tools/example_tool.py"),
            "TypeScript": ("tool.typescript.template.ts", "tools/example_tool.ts"),
            "JavaScript": ("tool.typescript.template.ts", "tools/example_tool.ts"),
            "Java": ("tool.java.template.java", "tools/ExampleTool.java"),
            "Go": ("tool.go.template.go", "tools/example_tool.go"),
        }
        generated = set()
        for lang in self.meta.get("primary_languages", []):
            if lang in lang_map:
                tmpl_name, output = lang_map[lang]
                if output not in generated:
                    t = TEMPLATES_DIR / tmpl_name
                    if t.exists():
                        self._write_file(output, t.read_text(encoding="utf-8"))
                        generated.add(output)

    def _generate_memory_schema(self) -> None:
        schema = {
            "version": "2.3.3",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "project": self.meta.get("project_name", "Project"),
            "languages": self.meta.get("primary_languages", []),
            "frameworks": self.meta.get("frameworks", []),
            "conventions": {
                "test_framework": self.meta.get("test_framework", "unknown"),
                "entry_points": self.meta.get("entry_points", []),
            },
        }
        self._write_file("memory/schema.md", f"```json\n{json.dumps(schema, indent=2, ensure_ascii=False)}\n```\n")


# ============================================================================
# Pre-commit Hook Management
# ============================================================================

def install_hooks(target_path: Path) -> None:
    git_hooks_dir = target_path / ".git" / "hooks"
    hook_path = git_hooks_dir / "pre-commit"
    hook_content = '''#!/bin/sh
# Installed by AgentReady (https://github.com/vb-nattamai/agent-ready)
CHANGED=$(git diff --cached --name-only | grep -E '\\.(py|ts|js|java|go|rs|cs|rb)$')
if [ -z "$CHANGED" ]; then exit 0; fi
TOOLKIT=$(git config --get agentic.toolkit-path)
if [ -z "$TOOLKIT" ]; then
  echo "[agentic-ready] Skipping — agentic.toolkit-path not set."
  exit 0
fi
echo "[agentic-ready] Refreshing agent-context.json..."
python "$TOOLKIT/scripts/run_transformer.py" --target . --only context --force --quiet
if ! git diff --quiet agent-context.json; then
  git add agent-context.json
fi
'''
    hook_path.parent.mkdir(parents=True, exist_ok=True)
    if hook_path.exists() and "agentic-ready" in hook_path.read_text():
        print(f"⚠️  Pre-commit hook already exists at {hook_path}.")
        return
    hook_path.write_text(hook_content, encoding="utf-8")
    os.chmod(hook_path, 0o755)
    print(f"✅ Pre-commit hook installed in {hook_path}")
    print("Run: git config agentic.toolkit-path /absolute/path/to/agent-ready")


# ============================================================================
# Context Verification
# ============================================================================

def verify(target_path: Path) -> None:
    context_file = target_path / "agent-context.json"
    if not context_file.exists():
        print("⚠️  agent-context.json not found.")
        return
    try:
        context_json = json.loads(context_file.read_text())
    except json.JSONDecodeError:
        print("❌ agent-context.json is malformed JSON")
        return
    claude_md = (target_path / "CLAUDE.md").read_text() if (target_path / "CLAUDE.md").exists() else ""
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        prompt = f"""Given the following agent-context.json and CLAUDE.md, answer in valid JSON only:
{{"detected_entry_point": "?", "detected_test_command": "?", "detected_primary_language": "?"}}

agent-context.json:
{json.dumps(context_json, indent=2)}

CLAUDE.md:
{claude_md}"""
        message = client.messages.create(model="claude-haiku-4-5-20251001", max_tokens=256, messages=[{"role": "user", "content": prompt}])
        try:
            llm_answers = json.loads(message.content[0].text)
        except (json.JSONDecodeError, IndexError):
            print("⚠️  LLM response was not valid JSON.")
            return
        static = context_json.get("static", context_json)
        results = [
            ("entry_point", static.get("entry_point", "<unknown>"), llm_answers.get("detected_entry_point", "<unknown>")),
            ("test_command", static.get("test_command", "<unknown>"), llm_answers.get("detected_test_command", "<unknown>")),
            ("primary_language", static.get("primary_language", "<unknown>"), llm_answers.get("detected_primary_language", "<unknown>")),
        ]
        print()
        print("┌─────────────────────┬──────────────────────┬──────────────────────┬────────┐")
        print("│ Field               │ agent-context.json   │ LLM understood       │ Match  │")
        print("├─────────────────────┼──────────────────────┼──────────────────────┼────────┤")
        matched = 0
        for field, actual, understood in results:
            match = "✅" if str(actual).lower() in str(understood).lower() or str(understood).lower() in str(actual).lower() else "❌"
            if "✅" in match:
                matched += 1
            print(f"│ {field:<19} │ {str(actual)[:20]:<20} │ {str(understood)[:20]:<20} │ {match:<6} │")
        print("└─────────────────────┴──────────────────────┴──────────────────────┴────────┘")
        print(f"Verification score: {matched}/3")
        if matched < 2:
            sys.exit(1)
    except ImportError:
        print("⚠️  anthropic package not installed.")


# ============================================================================
# Agentic Readiness Scoring
# ============================================================================

def score(target_path: Path) -> dict[str, Any]:
    criteria = {
        "agent-context.json": (10, (target_path / "agent-context.json").exists()),
        "CLAUDE.md": (10, (target_path / "CLAUDE.md").exists()),
        "AGENTS.md": (10, (target_path / "AGENTS.md").exists()),
        "system_prompt.md": (5, (target_path / "system_prompt.md").exists() or (target_path / "agents" / "system_prompt.md").exists()),
        "tools/ has files": (10, any((target_path / "tools").glob("*")) if (target_path / "tools").exists() else False),
    }
    context_file = target_path / "agent-context.json"
    if context_file.exists():
        try:
            ctx = json.loads(context_file.read_text())
            static = ctx.get("static", ctx)
            entry_point = static.get("entry_point", "")
            criteria["entry_point exists"] = (10, bool(entry_point) and (target_path / entry_point).exists())
            criteria["test_command set"] = (10, bool(static.get("test_command") or ctx.get("commands", {}).get("test")))
            criteria["restricted_write_paths"] = (10, len(static.get("restricted_write_paths", [])) > 0)
            criteria["environment_variables"] = (10, len(static.get("environment_variables", [])) > 0)
            criteria["domain_concepts >= 3"] = (5, len(static.get("domain_concepts", [])) >= 3)
        except json.JSONDecodeError:
            pass
    criteria["OpenAPI spec"] = (5, any([
        list(target_path.glob("**/openapi.yaml")), list(target_path.glob("**/openapi.yml")),
        list(target_path.glob("**/openapi.json")), list(target_path.glob("**/swagger.yaml")),
        list(target_path.glob("**/swagger.yml")), list(target_path.glob("**/swagger.json")),
    ]))
    criteria["CI config exists"] = (5,
        any(target_path.glob(".github/workflows/*.yml"))
        or any(target_path.glob(".gitea/workflows/*.yml"))
        or (target_path / ".travis.yml").exists()
        or (target_path / ".circleci/config.yml").exists()
        or (target_path / "Jenkinsfile").exists()
    )
    total = 0
    table_rows = []
    for criterion, (points, achieved) in criteria.items():
        if achieved:
            total += points
            table_rows.append((f"✅ {criterion}", f"+{points}"))
        else:
            table_rows.append((f"⬜ {criterion}", "+ 0"))
    return {"score": total, "max": 100, "rows": table_rows}


# ============================================================================
# LLM-First Pipeline (--llm flag)
# ============================================================================

def _run_llm_pipeline(
    target: Path,
    only: str | None,
    dry_run: bool,
    force: bool,
    quiet: bool,
) -> list[tuple[str, str]]:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("❌ ANTHROPIC_API_KEY environment variable is not set.")
        sys.exit(1)
    try:
        import anthropic
        from agent_ready import analyser, generator
    except ImportError as exc:
        print(f"❌ Missing dependency for LLM mode: {exc}")
        print("   Run: pip install anthropic")
        sys.exit(1)
    client = anthropic.Anthropic(api_key=api_key)
    if not quiet:
        print("\n🤖 LLM-first mode active")
        print("─" * 50)
    analysis = analyser.run(target, client, quiet=quiet)
    if not quiet:
        print("\n✍️  Generating files with Claude Sonnet...")
    gen = generator.LLMGenerator(target=target, analysis=analysis, client=client, dry_run=dry_run, force=force, quiet=quiet)
    if only:
        return gen.generate_only(only)
    return gen.generate_all()


# ============================================================================
# Eval Pipeline (--eval / --eval-only flags)
# ============================================================================

def _run_eval_pipeline(
    target: Path,
    fail_level: float = 0.0,
    quiet: bool = False,
) -> dict[str, Any]:
    """
    Run evaluation: measure whether generated context files improve AI responses.
    Asks 9 questions with and without context, judges both, reports improvement delta.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("❌ ANTHROPIC_API_KEY environment variable is not set.")
        sys.exit(1)
    try:
        import anthropic
        from agent_ready import evaluator
    except ImportError as exc:
        print(f"❌ Missing dependency for eval mode: {exc}")
        print("   Run: pip install anthropic")
        sys.exit(1)
    client = anthropic.Anthropic(api_key=api_key)
    try:
        result = evaluator.run_eval(target=target, client=client, fail_level=fail_level, quiet=quiet)
        report_path = evaluator.save_eval_report(target, result)
        if not quiet:
            print(f"\n  📄 Full report saved: {report_path.relative_to(target)}")
        if fail_level > 0 and not result["passed"]:
            print(f"\n❌ Eval failed: pass rate {int(result['pass_rate'] * 100)}% is below threshold {int(fail_level * 100)}%")
            sys.exit(1)
        return result
    except ValueError as e:
        print(f"❌ {e}")
        sys.exit(1)


# ============================================================================
# CLI
# ============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Transform any repository into an AI-agent-ready codebase.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  agent-ready --target /path/to/repo
  agent-ready --target /path/to/repo --llm
  agent-ready --target /path/to/repo --llm --only agents
  agent-ready --target /path/to/repo --dry-run
  agent-ready --target /path/to/repo --llm --eval
  agent-ready --target /path/to/repo --eval-only
  agent-ready --target /path/to/repo --eval-only --fail-level 0.8
        """,
    )
    parser.add_argument("--target", "-t", required=True, help="Target repository path")
    parser.add_argument(
        "--llm", action="store_true",
        help="LLM-first mode: Claude Opus analyses the code, Claude Sonnet writes every file. Requires ANTHROPIC_API_KEY.",
    )
    parser.add_argument(
        "--only", choices=["agents", "tools", "context", "memory"],
        help="Generate only specific category",
    )
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument(
        "--provider", choices=["anthropic", "openai", "gemini"], default="anthropic",
        help="LLM provider (static mode only)",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--install-hooks", action="store_true", help="Install pre-commit hook")
    parser.add_argument("--verify", action="store_true", help="Verify generated context with LLM")
    parser.add_argument("--quiet", action="store_true", help="Suppress non-essential output")
    parser.add_argument(
        "--eval", action="store_true",
        help="After transformation, evaluate whether context files improve AI responses. Requires ANTHROPIC_API_KEY.",
    )
    parser.add_argument(
        "--eval-only", action="store_true",
        help="Skip transformation, run evaluation only against existing context files. Requires ANTHROPIC_API_KEY.",
    )
    parser.add_argument(
        "--fail-level", type=float, default=0.0, metavar="0.0-1.0",
        help="Exit 1 if eval pass rate is below this threshold. E.g. 0.8 = 80%%. Use as CI gate.",
    )

    args = parser.parse_args()
    target = Path(args.target).resolve()

    if not target.is_dir():
        print(f"❌ Directory not found: {target}")
        sys.exit(1)

    if args.install_hooks:
        install_hooks(target)
        return

    if args.verify:
        verify(target)
        return

    # ── Eval-only path — skip transformation entirely ─────────────────────────
    if args.eval_only:
        if not args.quiet:
            print()
            print("╔══════════════════════════════════════════════╗")
            print("║   🧪 AgentReady Evaluator v2.0              ║")
            print("╚══════════════════════════════════════════════╝")
            print()
        _run_eval_pipeline(target=target, fail_level=args.fail_level, quiet=args.quiet)
        return

    if not args.quiet:
        print()
        print("╔══════════════════════════════════════════════╗")
        if args.llm:
            print("║   🤖 AgentReady Transformer v2.0 (LLM)     ║")
        else:
            print("║   🤖 AgentReady Transformer v2.0           ║")
        print("╚══════════════════════════════════════════════╝")
        print()

    # ── LLM-first path ────────────────────────────────────────────────────────
    if args.llm:
        generated = _run_llm_pipeline(
            target=target, only=args.only, dry_run=args.dry_run,
            force=args.force, quiet=args.quiet,
        )

    # ── Static / template path ────────────────────────────────────────────────
    else:
        analyzer = RepoAnalyzer(target)
        metadata = analyzer.analyze()
        if not args.quiet:
            print()
        generator_obj = AgenticGenerator(target, metadata, dry_run=args.dry_run, force=args.force)
        generated = generator_obj.generate_only(args.only) if args.only else generator_obj.generate_all()

    # ── Scoring + summary ─────────────────────────────────────────────────────
    readiness = score(target)

    if not args.quiet:
        print()
        print("─" * 50)
        mode_str = "[DRY RUN] " if args.dry_run else ""
        print(f"✅ {mode_str}Transformation Complete")
        print("─" * 50)
        print()
        print("  Generated Files:")
        for filepath, status in generated:
            print(f"    {status[:2]} {filepath}")
        print()
        print("──────────────────────────────────────────────")
        print(f"  AGENTIC READINESS SCORE: {readiness['score']} / {readiness['max']}")
        print("──────────────────────────────────────────────")
        for criterion, points in readiness["rows"]:
            print(f"  {criterion:<42} {points:>4}")
        if readiness["score"] < 100:
            print()
            print("  💡 To improve your score:")
            if not (target / "agent-context.json").exists():
                print("     - Generate agent-context.json (run without --only flag)")
            if not any(target.glob("**/openapi.{yaml,json,yml}")):
                print("     - Add an OpenAPI spec (openapi.yaml)")
            if not args.llm:
                print("     - Re-run with --llm for real content instead of placeholders")
        print("──────────────────────────────────────────────")
        print()

    # ── Optional eval after transformation ────────────────────────────────────
    if args.eval and not args.dry_run:
        _run_eval_pipeline(target=target, fail_level=args.fail_level, quiet=args.quiet)


if __name__ == "__main__":
    main()