"""
AgentReady — LLM Generator (Phase 3)

Takes the structured analysis JSON produced by analyser.py and uses
an LLM to write each output file from scratch.

Uses LiteLLM — works with Anthropic, OpenAI, and Google providers.
"""

from __future__ import annotations

import json
import random
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

GENERATION_HEADER = (
    "<!-- Generated by AgentReady (LLM-first mode) | "
    "Dynamic section: do not edit manually. "
    "Static section in agent-context.json: safe to edit. -->"
)


# ── LiteLLM call with retry ───────────────────────────────────────────────────

def _call(
    model: str,
    prompt: str,
    max_tokens: int = 3000,
) -> str:
    try:
        import litellm
    except ImportError:
        raise ImportError("litellm not installed. Run: pip install 'agent-ready[ai]'")

    last_error = None
    for attempt in range(5):
        try:
            response = litellm.completion(
                model=model,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            err_str = str(e).lower()
            if any(x in err_str for x in ["529", "overloaded", "service unavailable", "rate limit", "429"]):
                last_error = e
                if attempt < 4:
                    wait = (60 * (attempt + 1)) + random.uniform(0, 10)
                    print(f"  ⚠️  API overloaded, retrying in {int(wait)}s... (attempt {attempt + 1}/5)")
                    time.sleep(wait)
                else:
                    raise last_error
            else:
                raise
    raise last_error


def _analysis_block(analysis: dict[str, Any]) -> str:
    return json.dumps(analysis, indent=2)


def _pitfalls_block(analysis: dict[str, Any]) -> str:
    pitfalls = analysis.get("potential_pitfalls", [])
    if not pitfalls:
        return "No pitfalls detected."
    return "\n".join(f"{i+1}. {p}" for i, p in enumerate(pitfalls))


# ── agent-context.json ────────────────────────────────────────────────────────

def build_agent_context(
    analysis: dict[str, Any],
    existing_static: dict[str, Any] | None = None,
) -> str:
    static = existing_static or {
        "project_name": analysis.get("project_name", ""),
        "description": analysis.get("description", ""),
        "primary_language": analysis.get("primary_language", ""),
        "frameworks": analysis.get("frameworks", []),
        "entry_point": analysis.get("entry_point", ""),
        "test_command": analysis.get("test_command", ""),
        "restricted_write_paths": analysis.get("restricted_write_paths", []),
        "environment_variables": analysis.get("environment_variables", []),
        "domain_concepts": [
            f"{c['term']}: {c['definition']}"
            for c in analysis.get("domain_concepts", [])
        ],
    }

    dynamic = {
        "last_scanned": datetime.now(timezone.utc).isoformat(),
        "secondary_languages": analysis.get("secondary_languages", []),
        "build_system": analysis.get("build_system", ""),
        "build_command": analysis.get("build_command", ""),
        "install_command": analysis.get("install_command", ""),
        "run_command": analysis.get("run_command", ""),
        "test_framework": analysis.get("test_framework", ""),
        "test_directory": analysis.get("test_directory", ""),
        "source_directories": analysis.get("source_directories", []),
        "module_layout": analysis.get("module_layout", {}),
        "architecture_summary": analysis.get("architecture_summary", ""),
        "key_components": analysis.get("key_components", []),
        "agent_safe_operations": analysis.get("agent_safe_operations", []),
        "agent_forbidden_operations": analysis.get("agent_forbidden_operations", []),
        "potential_pitfalls": analysis.get("potential_pitfalls", []),
        "conventions": {
            "naming": analysis.get("naming_convention", ""),
            "structure": analysis.get("structure_type", ""),
        },
        "has_ci": analysis.get("has_ci", False),
        "has_openapi": analysis.get("has_openapi", False),
    }

    return json.dumps({"static": static, "dynamic": dynamic}, indent=2)


# ── AGENTS.md ─────────────────────────────────────────────────────────────────

def generate_agents_md(model: str, analysis: dict[str, Any]) -> str:
    return _call(model, f"""\
Generate an AGENTS.md file for this repository.

AGENTS.md is the operating contract for GitHub Copilot and OpenAI agents.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections with SPECIFIC content — reference actual file paths,
class names, commands, and patterns found in this codebase. No generic advice.

1. ## Project Overview
   Name, what it actually does, language/framework/build tool.

2. ## Commands
   The exact verified commands — install, build, test, run, lint.

3. ## Safe Operations
   Specific things an agent IS permitted to do in this codebase.

4. ## Forbidden Operations
   Specific things an agent MUST NEVER do.
   Reference actual restricted_write_paths by name.

5. ## Domain Glossary
   Every term from domain_concepts, defined for zero-context readers.

6. ## Key Components
   Each entry from key_components: name, path, and responsibility.

7. ## Potential Pitfalls
   THIS SECTION IS CRITICAL. Write every item below verbatim as a warning.
   Do NOT summarise, generalise, or skip any item.

   Pitfalls found in this codebase:
{_pitfalls_block(analysis)}

   For each pitfall: what the agent will try to do, why it breaks things, what to do instead.

Write as if a senior engineer on this team authored it for an AI agent joining today.\
""")


# ── CLAUDE.md ─────────────────────────────────────────────────────────────────

def generate_claude_md(model: str, analysis: dict[str, Any]) -> str:
    return _call(model, f"""\
Generate a CLAUDE.md file for this repository.

CLAUDE.md is auto-loaded by Claude Code at the start of every session.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections as DIRECT INSTRUCTIONS.
Every rule must reference actual file paths, class names, or patterns.
No generic software engineering advice.

1. ## Critical Commands
   Use ONLY these commands — never invent alternatives:
   - Install:  {analysis.get("install_command", "see analysis")}
   - Build:    {analysis.get("build_command", "see analysis")}
   - Test:     {analysis.get("test_command", "see analysis")}
   - Run:      {analysis.get("run_command", "see analysis")}

2. ## Always Do
   6–8 specific rules for THIS codebase.

3. ## Never Do
   6–8 prohibitions referencing restricted_write_paths and agent_forbidden_operations.

4. ## Architecture Notes
   3–4 most important design decisions to understand.

5. ## Domain Context
   Key concepts for understanding the business logic.

6. ## Known Pitfalls — Read Before Writing Any Code
   THIS SECTION IS CRITICAL. Copy every pitfall below VERBATIM.
   Do NOT add generic advice. Do NOT skip any item.

   Pitfalls found in this codebase:
{_pitfalls_block(analysis)}

7. ## After Every Change
   Specific checklist including the test command.\
""")


# ── system_prompt.md ──────────────────────────────────────────────────────────

def generate_system_prompt(model: str, analysis: dict[str, Any]) -> str:
    return _call(model, f"""\
Generate a system_prompt.md file for this repository.

This file is the system prompt for ANY LLM working on this codebase.
Paste-ready into the system field of any LLM API call.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write in second person ("You are working on..."). Cover:
- What this project does
- Full tech stack: language, frameworks, build tool
- Exact commands to install, build, test, run
- What the LLM must never touch (reference restricted_write_paths by name)
- Domain concepts for understanding the business logic
- Coding conventions
- Key components and responsibilities
- Every pitfall verbatim:
{_pitfalls_block(analysis)}

Target ~400–600 words.\
""")


# ── memory/schema.md ──────────────────────────────────────────────────────────

def generate_memory_schema(model: str, analysis: dict[str, Any]) -> str:
    return _call(model, f"""\
Generate a memory/schema.md file for this repository.

This file defines what an AI agent should track as working memory.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Define a YAML schema for agent memory. Reference actual domain_concepts and key_components.

Include:
1. session_state — current task, status, phase
2. decisions_made — format for recording WHY a decision was made
3. files_modified — what to track about each changed file
4. tests_run — test results and coverage
5. open_questions — items needing human review
6. domain_state — language/framework-specific state worth tracking

Use YAML format with inline comments.\
""")


# ── mcp.json ──────────────────────────────────────────────────────────────────

def generate_mcp_json(analysis: dict[str, Any]) -> str:
    lang = analysis.get("primary_language", "").lower()
    runtime_map = {
        "python": "python",
        "typescript": "node",
        "javascript": "node",
        "java": "java",
        "kotlin": "java",
        "go": "go",
        "rust": "cargo",
        "ruby": "ruby",
    }
    runtime = runtime_map.get(lang, "python")

    mcp = {
        "_comment": GENERATION_HEADER,
        "mcpServers": {
            f"{analysis.get('project_name', 'project').lower().replace(' ', '-')}-tools": {
                "command": runtime,
                "args": ["tools/example_tool" + (".py" if runtime == "python" else "")],
                "env": {var: f"${{{var}}}" for var in analysis.get("environment_variables", [])[:5]},
            }
        },
    }
    return json.dumps(mcp, indent=2)


# ── Orchestrator ──────────────────────────────────────────────────────────────

class LLMGenerator:
    def __init__(
        self,
        target: Path,
        analysis: dict[str, Any],
        generation_model: str,
        dry_run: bool = False,
        force: bool = False,
        quiet: bool = False,
    ):
        self.target = target
        self.analysis = analysis
        self.model = generation_model
        self.dry_run = dry_run
        self.force = force
        self.quiet = quiet
        self.generated: list[tuple[str, str]] = []

    def generate_all(self) -> list[tuple[str, str]]:
        self._agent_context()
        self._agents_md()
        self._claude_md()
        self._system_prompt()
        self._mcp_json()
        self._memory_schema()
        return self.generated

    def generate_only(self, category: str) -> list[tuple[str, str]]:
        dispatch = {
            "agents": lambda: (self._agents_md(), self._claude_md(), self._system_prompt()),
            "context": self._agent_context,
            "memory": self._memory_schema,
            "tools": lambda: None,
        }
        fn = dispatch.get(category)
        if fn is None:
            raise ValueError(f"Unknown category: {category!r}")
        fn()
        return self.generated

    def _agent_context(self) -> None:
        existing_static: dict[str, Any] | None = None
        ctx_path = self.target / "agent-context.json"
        if ctx_path.exists():
            try:
                existing = json.loads(ctx_path.read_text())
                existing_static = existing.get("static")
                if not self.quiet and existing_static:
                    print("  ℹ️  Existing static section found — preserving it")
            except Exception:
                pass
        content = build_agent_context(self.analysis, existing_static)
        self._write("agent-context.json", content, always_overwrite=True)

    def _agents_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating AGENTS.md...")
        self._write("AGENTS.md", generate_agents_md(self.model, self.analysis))

    def _claude_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating CLAUDE.md...")
        self._write("CLAUDE.md", generate_claude_md(self.model, self.analysis))

    def _system_prompt(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating system_prompt.md...")
        self._write("system_prompt.md", generate_system_prompt(self.model, self.analysis))

    def _mcp_json(self) -> None:
        self._write("mcp.json", generate_mcp_json(self.analysis))

    def _memory_schema(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating memory/schema.md...")
        self._write("memory/schema.md", generate_memory_schema(self.model, self.analysis))

    def _write(self, rel_path: str, content: str, always_overwrite: bool = False) -> None:
        full_path = self.target / rel_path
        already_exists = full_path.exists()

        if already_exists and not self.force and not always_overwrite:
            if not self.quiet:
                print(f"  ⏭️  {rel_path} (exists — use --force to overwrite)")
            self.generated.append((rel_path, "⏭️  Skipped"))
        elif self.dry_run:
            if not self.quiet:
                print(f"  📝 [dry-run] {rel_path}")
            self.generated.append((rel_path, "📝 (dry-run)"))
        else:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            status = "🔄 Updated" if already_exists else "✅ Created"
            if not self.quiet:
                print(f"  {status[:2]} {rel_path}")
            self.generated.append((rel_path, status))