"""
AgentReady — LLM Generator (Phase 3)

Takes the structured analysis JSON produced by analyser.py and uses
Claude Sonnet to write each output file from scratch.

No templates are filled here — every file is written by the LLM based
on what it actually found in the codebase. The result is real content,
not placeholders.

This module is only used when --llm is passed to the CLI.
The existing AgenticGenerator in cli.py is unaffected.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import anthropic

# ── Models ────────────────────────────────────────────────────────────────────

GENERATION_MODEL = "claude-sonnet-4-6"

GENERATION_HEADER = (
    "<!-- Generated by AgentReady (LLM-first mode) | "
    "Dynamic section: do not edit manually. "
    "Static section in agent-context.json: safe to edit. -->"
)


# ── Internal helpers ──────────────────────────────────────────────────────────

def _call(
    client: anthropic.Anthropic,
    prompt: str,
    max_tokens: int = 3000,
) -> str:
    """Single Sonnet generation call."""
    response = client.messages.create(
        model=GENERATION_MODEL,
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text.strip()


def _analysis_block(analysis: dict[str, Any]) -> str:
    """Compact JSON representation of the analysis for prompt injection."""
    # Trim source-heavy fields that aren't needed in generation prompts
    slim = {k: v for k, v in analysis.items()}
    return json.dumps(slim, indent=2)


# ── agent-context.json ────────────────────────────────────────────────────────

def build_agent_context(
    analysis: dict[str, Any],
    existing_static: dict[str, Any] | None = None,
) -> str:
    """
    Build agent-context.json with a static/dynamic split.

    If an existing static section is provided it is preserved exactly —
    only the dynamic section is regenerated.
    """
    static = existing_static or {
        "project_name": analysis.get("project_name", ""),
        "description": analysis.get("description", ""),
        "primary_language": analysis.get("primary_language", ""),
        "frameworks": analysis.get("frameworks", []),
        "entry_point": analysis.get("entry_point", ""),
        "test_command": analysis.get("test_command", ""),
        "restricted_write_paths": analysis.get("restricted_write_paths", []),
        "environment_variables": analysis.get("environment_variables", []),
        "domain_concepts": [
            f"{c['term']}: {c['definition']}"
            for c in analysis.get("domain_concepts", [])
        ],
    }

    dynamic = {
        "last_scanned": datetime.now(timezone.utc).isoformat(),
        "secondary_languages": analysis.get("secondary_languages", []),
        "build_system": analysis.get("build_system", ""),
        "build_command": analysis.get("build_command", ""),
        "install_command": analysis.get("install_command", ""),
        "run_command": analysis.get("run_command", ""),
        "test_framework": analysis.get("test_framework", ""),
        "test_directory": analysis.get("test_directory", ""),
        "source_directories": analysis.get("source_directories", []),
        "module_layout": analysis.get("module_layout", {}),
        "architecture_summary": analysis.get("architecture_summary", ""),
        "key_components": analysis.get("key_components", []),
        "agent_safe_operations": analysis.get("agent_safe_operations", []),
        "agent_forbidden_operations": analysis.get("agent_forbidden_operations", []),
        "potential_pitfalls": analysis.get("potential_pitfalls", []),
        "conventions": {
            "naming": analysis.get("naming_convention", ""),
            "structure": analysis.get("structure_type", ""),
        },
        "has_ci": analysis.get("has_ci", False),
        "has_openapi": analysis.get("has_openapi", False),
    }

    return json.dumps({"static": static, "dynamic": dynamic}, indent=2)


# ── AGENTS.md ─────────────────────────────────────────────────────────────────

def generate_agents_md(client: anthropic.Anthropic, analysis: dict[str, Any]) -> str:
    return _call(client, f"""\
Generate an AGENTS.md file for this repository.

AGENTS.md is the operating contract for GitHub Copilot and OpenAI agents.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections with SPECIFIC content — reference actual file paths,
class names, commands, and patterns found in this codebase. No generic advice.

1. ## Project Overview
   Name, what it actually does, language/framework/build tool.

2. ## Commands
   The exact verified commands — install, build, test, run, lint.
   Use only what appears in the analysis.

3. ## Safe Operations
   Specific things an agent IS permitted to do in this codebase.
   Use agent_safe_operations from the analysis as the basis.

4. ## Forbidden Operations
   Specific things an agent MUST NEVER do.
   Reference actual restricted_write_paths by name.

5. ## Domain Glossary
   Every term from domain_concepts, written so an agent with zero
   domain knowledge can understand the business logic.

6. ## Key Components
   Each entry from key_components: name, path, and responsibility.

7. ## Potential Pitfalls
   Every item from potential_pitfalls, phrased as a warning.

Write as if a senior engineer on this team authored it specifically for
an AI agent joining the project today.\
""")


# ── CLAUDE.md ─────────────────────────────────────────────────────────────────

def generate_claude_md(client: anthropic.Anthropic, analysis: dict[str, Any]) -> str:
    return _call(client, f"""\
Generate a CLAUDE.md file for this repository.

CLAUDE.md is auto-loaded by Claude Code at the start of every session.
It is the most important context file Claude will read.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections as DIRECT INSTRUCTIONS to Claude.
Every rule must reference actual file paths, class names, or patterns
found in this codebase. No generic software engineering advice.

1. ## Critical Commands
   Claude must use ONLY these commands — never invent alternatives:
   - Install:  {analysis.get("install_command", "see analysis")}
   - Build:    {analysis.get("build_command", "see analysis")}
   - Test:     {analysis.get("test_command", "see analysis")}
   - Run:      {analysis.get("run_command", "see analysis")}

2. ## Always Do
   6–8 specific rules Claude must always follow for THIS codebase.
   Example style: "Always run {analysis.get("test_command")} after
   changing any class in [actual path from key_components]."

3. ## Never Do
   6–8 specific prohibitions referencing restricted_write_paths
   and agent_forbidden_operations from the analysis.

4. ## Architecture Notes
   The 3–4 most important things Claude must understand about how
   this system is designed (from architecture_summary and key_components).

5. ## Domain Context
   The key domain concepts explained so Claude understands the
   business logic, not just the syntax.

6. ## After Every Change
   A specific checklist Claude must complete after modifying this codebase.
   Include the test command and any lint/format steps found in the analysis.\
""")


# ── system_prompt.md ──────────────────────────────────────────────────────────

def generate_system_prompt(client: anthropic.Anthropic, analysis: dict[str, Any]) -> str:
    return _call(client, f"""\
Generate a system_prompt.md file for this repository.

This file is used as the system prompt for ANY LLM working on this codebase.
It should be paste-ready into the system field of any LLM interface.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write a complete, production-ready system prompt. Write in second person
("You are working on..."). Cover:

- What this project is and what it does (from description + architecture_summary)
- Full tech stack: language, frameworks, build tool
- Exact commands to install, build, test, and run
- What the LLM must never touch (reference restricted_write_paths by name)
- Domain concepts the LLM needs to reason about the business logic
- Coding conventions: naming, structure, patterns (from naming_convention, structure_type)
- Brief description of key components and their responsibilities

Length: comprehensive enough to be useful, concise enough to fit a context window.
Target ~400–600 words.\
""")


# ── memory/schema.md ──────────────────────────────────────────────────────────

def generate_memory_schema(client: anthropic.Anthropic, analysis: dict[str, Any]) -> str:
    return _call(client, f"""\
Generate a memory/schema.md file for this repository.

This file defines what an AI agent should track as working memory
across a coding session on this codebase.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Define a structured YAML schema for agent memory. Tailor every section
to this specific project — reference actual domain_concepts, key_components,
and the primary language ({analysis.get("primary_language", "")}) /
frameworks ({", ".join(analysis.get("frameworks", []))}).

Include these sections:

1. session_state — current task, status, what phase of work we're in
2. decisions_made — format for recording WHY a technical decision was made
3. files_modified — what to track about each changed file and the reason
4. tests_run — format for recording test results and coverage
5. open_questions — items needing human review or clarification
6. domain_state — {analysis.get("primary_language","")}-specific or
   framework-specific state worth tracking across turns

Use YAML format for schema definitions with inline comments explaining each field.\
""")


# ── mcp.json ──────────────────────────────────────────────────────────────────

def generate_mcp_json(analysis: dict[str, Any]) -> str:
    """
    Generate mcp.json. This one is deterministic — no LLM needed.
    The runtime command is inferred from the primary language.
    """
    lang = analysis.get("primary_language", "").lower()
    runtime_map = {
        "python": "python",
        "typescript": "node",
        "javascript": "node",
        "java": "java",
        "go": "go",
        "rust": "cargo",
        "ruby": "ruby",
    }
    runtime = runtime_map.get(lang, "python")

    mcp = {
        "_comment": GENERATION_HEADER,
        "mcpServers": {
            f"{analysis.get('project_name', 'project').lower().replace(' ', '-')}-tools": {
                "command": runtime,
                "args": ["tools/example_tool" + (".py" if runtime == "python" else "")],
                "env": {var: f"${{{var}}}" for var in analysis.get("environment_variables", [])[:5]},
            }
        },
    }
    return json.dumps(mcp, indent=2)


# ── Orchestrator ──────────────────────────────────────────────────────────────

class LLMGenerator:
    """
    Orchestrates Phase 3: writes all output files using Claude Sonnet.

    Usage:
        gen = LLMGenerator(target, analysis, client, dry_run=False, force=False)
        gen.generate_all()           # full run
        gen.generate_only("agents")  # selective
    """

    def __init__(
        self,
        target: Path,
        analysis: dict[str, Any],
        client: anthropic.Anthropic,
        dry_run: bool = False,
        force: bool = False,
        quiet: bool = False,
    ):
        self.target = target
        self.analysis = analysis
        self.client = client
        self.dry_run = dry_run
        self.force = force
        self.quiet = quiet
        self.generated: list[tuple[str, str]] = []  # (rel_path, status)

    # ── Public API ────────────────────────────────────────────────────────────

    def generate_all(self) -> list[tuple[str, str]]:
        """Generate every output file."""
        self._agent_context()
        self._agents_md()
        self._claude_md()
        self._system_prompt()
        self._mcp_json()
        self._memory_schema()
        return self.generated

    def generate_only(self, category: str) -> list[tuple[str, str]]:
        """Generate only files belonging to the given category."""
        dispatch = {
            "agents": lambda: (self._agents_md(), self._claude_md(), self._system_prompt()),
            "context": self._agent_context,
            "memory": self._memory_schema,
            "tools": lambda: None,  # tool templates stay with the static generator
        }
        fn = dispatch.get(category)
        if fn is None:
            raise ValueError(f"Unknown category: {category!r}")
        fn()
        return self.generated

    # ── Individual file generators ────────────────────────────────────────────

    def _agent_context(self) -> None:
        # Preserve existing static section if present
        existing_static: dict[str, Any] | None = None
        ctx_path = self.target / "agent-context.json"
        if ctx_path.exists():
            try:
                existing = json.loads(ctx_path.read_text())
                existing_static = existing.get("static")
                if not self.quiet and existing_static:
                    print("  ℹ️  Existing static section found — preserving it")
            except Exception:
                pass

        content = build_agent_context(self.analysis, existing_static)
        self._write("agent-context.json", content, always_overwrite=True)

    def _agents_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating AGENTS.md...")
        content = generate_agents_md(self.client, self.analysis)
        self._write("AGENTS.md", content)

    def _claude_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating CLAUDE.md...")
        content = generate_claude_md(self.client, self.analysis)
        self._write("CLAUDE.md", content)

    def _system_prompt(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating system_prompt.md...")
        content = generate_system_prompt(self.client, self.analysis)
        self._write("system_prompt.md", content)

    def _mcp_json(self) -> None:
        content = generate_mcp_json(self.analysis)
        self._write("mcp.json", content)

    def _memory_schema(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating memory/schema.md...")
        content = generate_memory_schema(self.client, self.analysis)
        self._write("memory/schema.md", content)

    # ── File writer ───────────────────────────────────────────────────────────

    def _write(
        self,
        rel_path: str,
        content: str,
        always_overwrite: bool = False,
    ) -> None:
        """Write a file and record its status."""
        full_path = self.target / rel_path
        already_exists = full_path.exists()

        if already_exists and not self.force and not always_overwrite:
            status = "⏭️  Skipped"
            if not self.quiet:
                print(f"  ⏭️  {rel_path} (exists — use --force to overwrite)")
        elif self.dry_run:
            status = "📝 (dry-run)"
            if not self.quiet:
                print(f"  📝 [dry-run] {rel_path}")
        else:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            status = "🔄 Updated" if already_exists else "✅ Created"
            if not self.quiet:
                print(f"  {status[:2]} {rel_path}")

        self.generated.append((rel_path, status))